#!/bin/bash

export ANDROID_HOME="/opt/android"
export TARGET_PORT=6080
export HOSTNAME=79fd11b94491
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
export VIDEO_PATH=/tmp/video
export APPIUM_VERSION=1.22.3
export APPIUM_LOG=/var/log/supervisor/appium.log
export PWD=/appiumcicl
export HOME=/root
export BROWSER=android
export SDK_VERSION=commandlinetools-linux-8512546_latest
export APP_TYPE=Device
export DEBIAN_FRONTEND=noninteractive
export ANDROID_DOWNLOAD_PATH=/root
export REAL_DEVICE=true
export ANDROID_BUILD_TOOLS_VERSION=33.0.0
export LOCAL_PORT=5900
export TERM=xterm
export GA_API_VERSION=1
export SHLVL=1
export GA_TRACKING_ID=UA-133466903-1
export TIMEOUT=1
export GA=true
export SCREEN_WIDTH=1600
export PATH=/opt/android/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/opt/android/cmdline-tools/tools:/opt/android/cmdline-tools/tools/bin:/opt/android/platform-tools:/opt/android/build-tools
export ANDROID_TOOL_HOME=/opt/android/cmdline-tools
export BASE_IMAGE=
_=/usr/bin/printenv
